name: C++ CI - Tebak Dadu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Install Dependency
      run: sudo apt-get instal -y g++
      
    - name: Create Input File
      run: echo "6" > input.txt
      
    - name: Compile Dadu.cpp
      run: g++ -o main Dadu.cpp
      
    - name: Run Program
      run: ./main
